=== Nogas/Formgenerator/examples/xml/FormGenerator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.skien.de/FormGenerator" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fg="http://www.skien.de/FormGenerator">

<!-- 
    This XSD schema was developed using the 'venetian blind' design to meet the following 
    requirements of the XML structure to be validated
    - The elements contained are based on a hierarchical structure that is mapped by 
      expanding the defined types accordingly.
    - The various elements can be nested variably. This can be specified much more 
      clearly and in a more maintainable manner by using the types rather than specifying 
      each element individually.  
 -->
 
    <xs:element name="FormGenerator" type="fg:FormGeneratorType"/>

    <!--
        The Root element MUST contain exact one &lt;Form&gt; element as parent of the whole form definition.
    -->
    <xs:complexType name="FormGeneratorType" >
        <xs:sequence>
            <xs:element name="Form" type="fg:FormType"/>
        </xs:sequence>
    </xs:complexType>

    <!--
        The Form element is the one and only parent element of all further elements.
        
        It can contain any of the container-elements (Div, Fieldset, Line) or any of the
        simple elements defined in the package!
        There is no rule for the order, the elements appears in the form.
    -->
    <xs:complexType name="FormType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="fg:DivType" name="Div"/>
            <xs:element type="fg:FieldSetType" name="FieldSet"/>
            <xs:element type="fg:LineType" name="Line"/>
            <xs:element type="fg:StaticType" name="Static"/>
            <xs:element type="fg:HeaderType" name="Header"/>
            <xs:element type="fg:ButtonBoxType" name="ButtonBox"/>
            <xs:element type="fg:InputType" name="Input"/>
            <xs:element type="fg:ButtonType" name="Button"/>
            <xs:element type="fg:CheckType" name="Check"/>
            <xs:element type="fg:ColorType" name="Color"/>
            <xs:element type="fg:CurType" name="Cur"/>
            <xs:element type="fg:DateType" name="Date"/>
            <xs:element type="fg:FloatType" name="Float"/>
            <xs:element type="fg:ImageType" name="Image"/>
            <xs:element type="fg:IntType" name="Int"/>
            <xs:element type="fg:RadioGroupType" name="RadioGroup"/>
            <xs:element type="fg:RangeType" name="Range"/>
            <xs:element type="fg:SelectType" name="Select"/>
            <xs:element type="fg:TextAreaType" name="TextArea"/>
            <xs:element type="fg:TimeType" name="Time"/>
            <xs:element type="xs:string" name="Script"/>
        </xs:choice>
        <xs:attribute type="xs:string" name="id"/>
        <xs:attribute type="fg:ColWidthAttrib" name="colwidth"/>
        <xs:attribute type="fg:WidthDimAttrib" name="widthdim" default="%"/>
        <xs:attribute type="xs:string" name="style"/>
        <xs:attribute type="xs:string" name="class"/>
    </xs:complexType>

    <xs:complexType name="DivType">
        <xs:complexContent>
            <xs:extension base="fg:FormType">
                <xs:attribute type="xs:integer" name="width"/>
                <xs:attribute type="fg:DivAlignAttrib" name="align"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FieldSetType">
        <xs:complexContent>
            <xs:extension base="fg:FormType">
                <xs:attribute type="xs:string" name="legend"/>
                <xs:attribute type="fg:FieldSetTypeAttrib" name="type"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="LineType">
        <xs:complexContent>
            <xs:extension base="fg:FormType">
                <xs:attribute type="xs:string" name="label"/>
                <xs:attribute type="xs:string" name="horzline"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ElementType">
                <xs:attribute type="xs:string" name="style"/>
                <xs:attribute type="xs:string" name="class"/>
    </xs:complexType>

    <xs:complexType name="StaticType">
        <xs:complexContent>
            <xs:extension base="fg:ElementType">
                <xs:attribute type="xs:string" name="text"/>
                <xs:attribute type="fg:FlagsAttrib" name="flags"/>
                <xs:attribute type="xs:string" name="for"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="HeaderType">
        <xs:complexContent>
            <xs:extension base="fg:ElementType">
                <xs:attribute type="xs:string" name="text"/>
                <xs:attribute type="xs:integer" name="level"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

	<xs:complexType name="ButtonBoxType">
		<xs:complexContent>
            <xs:extension base="fg:ElementType">
				<xs:attribute type="fg:ButtonsAttrib" name="buttons"/>
				<xs:attribute type="fg:FlagsAttrib" name="flags"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <xs:complexType name="InputType">
        <xs:complexContent>
            <xs:extension base="fg:ElementType">
                <xs:attribute type="xs:string" name="id"/>
                <xs:attribute type="xs:string" name="name"/>
                <xs:attribute type="xs:string" name="size"/>
                <xs:attribute type="fg:FlagsAttrib" name="flags"/>
                <xs:attribute type="xs:integer" name="maxlength"/>
                <xs:attribute type="xs:string" name="placeholder"/>
                <xs:attribute type="xs:string" name="expandfolder"/>
                <xs:attribute type="xs:string" name="suffix"/>
                <xs:attribute type="xs:string" name="selectimg"/>
		        <xs:attribute type="xs:string" name="onclick"/>
                <xs:attribute type="xs:string" name="ondblclick"/>
                <xs:attribute type="xs:string" name="onchange"/>
                <xs:attribute type="xs:string" name="oninput"/>
                <xs:attribute type="xs:string" name="onfocus"/>
                <xs:attribute type="xs:string" name="onblur"/>
                <xs:attribute type="xs:string" name="onkeydown"/>
                <xs:attribute type="xs:string" name="onkeypress"/>
                <xs:attribute type="xs:string" name="onkeyup"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ButtonType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
		        <xs:attribute type="xs:string" name="text"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

	<xs:complexType name="CanvasType">
		<xs:complexContent>
            <xs:extension base="fg:InputType">
				<xs:attribute type="xs:integer" name="width"/>
				<xs:attribute type="xs:integer" name="height"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <xs:complexType name="CheckType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
		        <xs:attribute type="xs:string" name="btnvalue"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ColorType">
        <xs:complexContent>
            <xs:extension base="fg:InputType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CurType">
        <xs:complexContent>
            <xs:extension base="fg:InputType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="DateType">
        <xs:complexContent>
            <xs:extension base="fg:InputType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FloatType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
                <xs:attribute type="xs:integer" name="digits" default="1"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

	<xs:complexType name="ImageType">
		<xs:complexContent>
            <xs:extension base="fg:InputType">
				<xs:attribute type="xs:string" name="default"/>
				<xs:attribute type="xs:string" name="bindto"/>
				<xs:attribute type="xs:string" name="title"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <xs:complexType name="IntType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
		        <xs:attribute type="xs:integer" name="min"/>
		        <xs:attribute type="xs:integer" name="max"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RadioGroupType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
                <xs:sequence>
                    <xs:element type="fg:OptionType" name="option" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>            
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="RangeType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
                <xs:attribute type="xs:string" name="width"/>
		        <xs:attribute type="xs:integer" name="min"/>
		        <xs:attribute type="xs:integer" name="max"/>
		        <xs:attribute type="xs:integer" name="step"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SelectType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
                <xs:sequence>
                    <xs:element type="fg:OptionType" name="option" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>            
                <xs:attribute type="xs:string" name="selectbtntext"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TextAreaType">
        <xs:complexContent>
            <xs:extension base="fg:InputType">
                <xs:attribute type="xs:integer" name="rows"/>
                <xs:attribute type="xs:integer" name="cols"/>
                <xs:attribute type="xs:string" name="width"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TimeType">
        <xs:complexContent>
            <xs:extension base="fg:InputType"/>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="OptionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>    

	<xs:simpleType name="ColWidthAttrib">
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9]*(, ?[0-9]*)*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="WidthDimAttrib">
		<xs:restriction base="xs:string">
			<xs:enumeration value="%"/>
			<xs:enumeration value="px"/>
			<xs:enumeration value="pt"/>
			<xs:enumeration value="en"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DivAlignAttrib">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NONE"/>
			<xs:enumeration value="CLEAR"/>
			<xs:enumeration value="LEFT"/>
			<xs:enumeration value="RIGHT"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="FieldSetTypeAttrib">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TEXT"/>
			<xs:enumeration value="IMAGE"/>
		</xs:restriction>
	</xs:simpleType>
	
    <xs:simpleType name="FlagsAttrib">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ALIGN_LEFT"/>
                    <xs:enumeration value="MANDATORY"/>
                    <xs:enumeration value="HIDDEN"/>
                    <xs:enumeration value="READ_ONLY"/>
                    <xs:enumeration value="ALIGN_RIGHT"/>
                    <xs:enumeration value="ADD_DTU"/>
                    <xs:enumeration value="ADD_SELBTN"/>
                    <xs:enumeration value="HINT"/>
                    <xs:enumeration value="ERROR"/>
                    <xs:enumeration value="SELECT_BTN"/>
                    <xs:enumeration value="SHOW_VALUE"/>
                    <xs:enumeration value="BROWSE_SERVER"/>
                    <xs:enumeration value="DISABLED"/>
                    <xs:enumeration value="INFO"/>
                    <xs:enumeration value="ALIGN_CENTER"/>
                    <xs:enumeration value="ADD_DATE_PICKER"/>
                    <xs:enumeration value="ADD_TIME_PICKER"/>
                    <xs:enumeration value="NO_ZERO"/>
                    <xs:enumeration value="PASSWORD"/>
                    <xs:enumeration value="FILE"/>
                    <xs:enumeration value="ADD_CUR"/>
                    <xs:enumeration value="TRIM"/>
                    <xs:enumeration value="SET_JSON_DATA"/>
                    <xs:enumeration value="BOLD"/>
                    <xs:enumeration value="REPLACE_BR_CR"/>
                    <xs:enumeration value="HORZ_ARRANGE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>
    
    <xs:simpleType name="ButtonsAttrib">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="OK"/>
                    <xs:enumeration value="OPEN"/>
                    <xs:enumeration value="SAVE"/>
                    <xs:enumeration value="YES"/>
                    <xs:enumeration value="NO"/>
                    <xs:enumeration value="CANCEL"/>
                    <xs:enumeration value="CLOSE"/>
                    <xs:enumeration value="DISCARD"/>
                    <xs:enumeration value="APPLY"/>
                    <xs:enumeration value="RESET"/>
                    <xs:enumeration value="RETRY"/>
                    <xs:enumeration value="IGNORE"/>
                    <xs:enumeration value="BACK"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>    
	
</xs:schema>

=== Nogas/Formgenerator/SKien/Test/Formgenerator/testdata/AllElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<FormGenerator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.skien.de/FormGenerator"
    xsi:schemaLocation="http://www.skien.de/FormGenerator FormGenerator.xsd">
    <Form colwidth="25, 75">
        <Header text="Header" level="1"/>
        <Static text="Static" class="overview" for="strInput"/>
        <Div width="100">
            <FieldSet type="IMAGE" imageheight="20">
                <Line label="Test Line" for="strInput">
                    <Input name="strInput" size="100%" flags="MANDATORY" maxlength="100"/>
                </Line>
                <Line label="Test Line" for="btnTest">
                    <Button id="btnTest" text="Test" style="width: 50px;"/>
                </Line>
                <Line label="Test Line">
                    <Canvas id="canvasTest" width="200" height="200"/>
                </Line>
                <Line label="Test Line" for="bTest">
                    <Check name="bTest" btnvalue="set"/>
                </Line>
                <!--
                <Line label="Test Line">
                    <CKEdit name="strTest" rows="5" content-css="test.css" body-id="test_body_id"/>
                </Line>
                -->
                <Line label="Test Line">
                    <Color name="clrTest"/>
                </Line>
                <Line label="Test Line">
                    <Cur name="fltTest" size="10"/>
                </Line>
                <Line label="Test Line">
                    <Date name="dateTest" size="10"/>
                </Line>
                <Line label="Test Line">
                    <Float name="curTest" size="10" digits="3"/>
                </Line>
                <Line label="Test Line">
                    <Image name="imgTest" image="IMG_SEARCH" bindto="strTest" default="test.img"/>
                </Line>
                <Line label="CPU:">
                    <Meter name="fltTempCPU" width="100%" min="60" max="120.0" low="80.0" high="100.0" optimum="60.0"/>
                </Line>
                <Line label="GPU:">
                    <Meter name="fltTempGPU" width="100%" max="120.0" low="80.0" high="100.0"/>
                </Line>
                <Line label="Test Line">
                    <RadioGroup name="iTest">
                        <option value="0">zero</option>
                        <option value="1">one</option>
                    </RadioGroup>
                </Line>
                <Line label="Test Line">
                    <Range name="iTest" min="0" max="100" step="10"/>
                </Line>
                <Line label="Test Line">
                    <Select name="strGender" size="1" selectbtntext="Select" flags="SELECT_BTN"/>
                </Line>
                <Line label="Test Line">
                    <Select name="strSelect">
                        <option value="0">zero</option>
                        <option value="1">one</option>
                    </Select>
                </Line>
                <Line label="Your rating:">
                    <StarRate name="iRating">
                        <title>ungenÃ¼gend</title>
                        <title>mangelhaft</title>
                        <title>ausreichend</title>
                        <title>befriedigend</title>
                        <title>gut</title>
                        <title>sehr gut</title>
                    </StarRate>
                    <StarRate name="iRating1" submittitle="true"/>
                </Line>
                <Line label="Test Line">
                    <TextArea name="strTest" rows="5" cols="50"/>
                </Line>
                <Line label="Test Line">
                    <Int name="iInt" size="10"/>
                </Line>
                <Line label="Test Line">
                    <Time name="timeTest" size="10"/>
                </Line>
            </FieldSet>
        </Div>
        <ButtonBox buttons="SAVE DISCARD" flags="ALIGN_RIGHT"/>
        <Script>
            <![CDATA[
                function SelectImage()
                {
                    browseServer('strImage', 'imgImage', '/images');
                }
                function ResetImage()
                {
                    resetElement('imgImage');
                }
            ]]>
        </Script>
    </Form>
</FormGenerator>

=== Nogas/Formgenerator/examples/xml/SimpleForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<FormGenerator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.skien.de/FormGenerator"
    xsi:schemaLocation="http://www.skien.de/FormGenerator FormGenerator.xsd">
    
    <Form colwidth="20, 80">
        <Header text="Personnel data sheet" level="1"/>
        <FieldSet legend="Name">
            <Line label="Lastname:">
                <Input name="strLastname" size="100%" flags="MANDATORY" maxlength="50"/>
            </Line>
            <Line label="Firstname:">
                <Input name="strFirstname" size="100%" maxlength="50"/>
            </Line>
        </FieldSet>
        <FieldSet legend="Address">
            <Line label="Region:">
                <Input name="strRegion" size="100%" maxlength="50" placeholder="enter Region"/>
            </Line>
            <Line label="Street:">
                <Input name="strStreet" size="100%" maxlength="100"/>
            </Line>
            <Line label="Postcode, City:" colwidth="20, 20, 60">
                <Input name="strPostcode" size="90%" maxlength="10"/>
                <Input name="strCity" size="100%" maxlength="100"/>
            </Line>
        </FieldSet>
        <FieldSet legend="some personal Data" colwidth="20, 30, 20, 30">
            <Line colwidth="0, 100">
                <Static text="This is an error message..." flags="ERROR BOLD"/>
            </Line>
            <Line colwidth="0, 100">
                <Static text="... and here are some informations" flags="INFO    BOLD"/>
            </Line>
            <Line label="Gender:">
                <Select name="strGender" size="1" flags="MANDATORY"/>
                <Static text="Date of Birth:" for="dateDoB"/>
                <Date name="dateDoB" flags="NO_ZERO ADD_DATE_PICKER"/>
            </Line>
            <Line label="Available from:">
                <Time name="timeAvailableFrom" flags="ADD_TIME_PICKER"/>
                <Static text="to:"/>
                <Time name="timeAvailableTo" flags="NO_ZERO ADD_TIME_PICKER "/>
            </Line>
            <Line label="Member due:">
                <Cur name="fltDue" size="10" flags="ADD_CUR"/>
                <Static text="extra fee:"/>
                <Cur name="fltExtra" size="10" flags="ADD_CUR NO_ZERO"/>
            </Line>
            <Line label="Weight:">
                <Float name="fltWeight" size="10" digits="1" suffix="kg"/>
            </Line>
            <Line label="Priority:">
                <Range name="iPriority" width="70%" min="1" max="10" step="2" flags="SHOW_VALUE"/>
                <Static text="category:"/>
                <Color name="strCatColor"/>
            </Line>
            <Line label="ResumÃ©:" colwidth="20, 80">
                <Input name="strResumeFile" size="calc(100% - 45px)" flags="BROWSE_SERVER READ_ONLY" expandfolder="files/"/>
            </Line>
        </FieldSet>
        <FieldSet legend="internal processing">
            <Line label="Validated:" colwidth="20, 50, 30">
                <Input name="strValidated" size="30" flags="ADD_DTU READ_ONLY"/>
                <Static text="with additional Hint" flags="HINT"/>
            </Line>
        </FieldSet>
        <ButtonBox buttons="SAVE DISCARD" flags="ALIGN_RIGHT"/>
    </Form>
</FormGenerator>

=== Nogas/Formgenerator/examples/xml/ColumnForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<FormGenerator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.skien.de/FormGenerator"
    xsi:schemaLocation="http://www.skien.de/FormGenerator FormGenerator.xsd">
    
    <Form colwidth="25, 75">
        <Header text="Personnel data sheet" level="1"/>
        <Div width="70" align="LEFT">
            <FieldSet legend="Name and Adress" id="col1">
                <Line label="Lastname:" widthdim="pt">
                    <Input name="strLastname" size="100%" flags="MANDATORY"/>
                </Line>
                <Line label="Firstname:">
                    <Input name="strFirstname" size="100%"/>
                </Line>
                <Line label="Street:">
                    <Input name="strStreet" size="100%"/>
                </Line>
                <Line label="Postcode, City:" colwidth="25, 25, 50">
                    <Input name="strPostcode" size="90%"/>
                    <Input name="strCity" size="100%"/>
                </Line>
                <Line horzline="true"/>
                <Line label="Gender:">
                    <RadioGroup name="strGender" flags="HORZ_ARRANGE"/>
                </Line>
                <Line label="Birthday:">
                    <Date name="dateDoB" flags="ADD_DATE_PICKER"/>
                </Line>
                <Line>
                    <Check name="bBoardMember" suffix="member of the board"/>
                </Line>
            </FieldSet>
        </Div>
        <Div width="30" align="LEFT">
            <FieldSet legend="Portrait" id="col2" colwidth="100">
                <Input name="strImage" flags="HIDDEN BROWSE_SERVER"/>
                <Image name="imgImage" onclick="SelectImage()" flags="ALIGN_CENTER" default=".\public\images\contact_empty.png" bindto="strImage" title="click to select an image"/>
                <Line colwidth="0, 50, 50">
                    <Button id="btnImageSelect" text="Select" onclick="SelectImage()" flags="ALIGN_CENTER"/>
                    <Button id="btnImageReset" text="Reset" onclick="ResetImage()" flags="ALIGN_CENTER"/>
                </Line>
            </FieldSet>
        </Div>
        <ButtonBox buttons="SAVE DISCARD" flags="ALIGN_RIGHT"/>
        <Script>
            <![CDATA[
                function SelectImage()
                {
                    browseServer('strImage', 'imgImage', '/images');
                }
                function ResetImage()
                {
                    resetElement('imgImage');
                }
            ]]>
        </Script>
    </Form>
</FormGenerator>

=== Nogas/Formgenerator/examples/xml/MeterForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<FormGenerator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.skien.de/FormGenerator"
    xsi:schemaLocation="http://www.skien.de/FormGenerator FormGenerator.xsd">
    
    <Form colwidth="40, 60">
        <Header text="Meter/StarRate Example" level="1"/>
        <FieldSet legend="Temperature">
            <Line label="CPU:">
                <Meter name="fltTempCPU" width="100%" min="60.0" max="120.0" low="80.0" high="100.0" optimum="60.0"/>
            </Line>
            <Line label="Grafic chip:">
                <Meter name="fltTempGPU" width="100%" min="60.0" max="120.0" low="80.0" high="100.0" optimum="60.0"/>
            </Line>
            <Line label="Power adapter:">
                <Meter name="fltTempPOW" width="100%" min="60.0" max="120.0" low="80.0" high="100.0" optimum="60.0"/>
            </Line>
        </FieldSet>
        <FieldSet legend="Rate the package">
            <Line label="Your rating:">
                <StarRate name="iRating" size="1">
                    <title>ungenÃ¼gend</title>
                    <title>mangelhaft</title>
                    <title>ausreichend</title>
                    <title>befriedigend</title>
                    <title>gut</title>
                    <title>sehr gut</title>
                </StarRate>
            </Line>
            <Line label="Tell me why:">
                <TextArea name="strReason" cols="50" rows="3" width="100%"/>
            </Line>
        </FieldSet>
        <ButtonBox buttons="OK" flags="ALIGN_RIGHT"/>
    </Form>
</FormGenerator>

=== Nogas/Formgenerator/examples/xml/QuickStart.xml
<?xml version="1.0" encoding="UTF-8"?>
<FormGenerator
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.skien.de/FormGenerator"
    xsi:schemaLocation="http://www.skien.de/FormGenerator FormGenerator.xsd">
    
    <Form colwidth="20, 80">
        <Header text="Quick Start Example" level="1"/>
        <FieldSet legend="Name">
            <Line label="Lastname:">
                <Input name="strLastname" size="100%" flags="MANDATORY" maxlength="50"/>
            </Line>
            <Line label="Firstname:">
                <Input name="strFirstname" size="100%" maxlength="50"/>
            </Line>
            <Line label="Nickname:">
                <Input name="strNickname" size="100%" maxlength="50"/>
            </Line>
        </FieldSet>
        <FieldSet legend="Personal Data" colwidth="20, 25, 20, 35">
            <Line label="Gender:">
                <Select name="strGender" size="1" flags="MANDATORY">
                    <option value=""></option>
                    <option value="m">male</option>
                    <option value="f">female</option>
                    <option value="d">diverse</option>
                </Select>
                <Static text="Birthday:"/>
                <Date name="dateDoB" flags="NO_ZERO ADD_DATE_PICKER"/>
            </Line>
            <Line label="Height:">
                <Int name="iHeight" size="4" suffix="cm"/>
                <Static text="Weight:"/>
                <Float name="fltWeight" size="5" digits="1" suffix="kg"/>
            </Line>
        </FieldSet>
        <ButtonBox buttons="SAVE DISCARD" flags="ALIGN_RIGHT"/>
    </Form>
</FormGenerator>
